### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by aiyan** [nu25/hoosky-bot#24]
Implement a `/help` command that outputs a list of commands and their functions.

### Extra

All commands have a help page, and running `/help [cmd-name]` outputs detailed usage documentation for that specific command.

**Comment by SamHaggans** [comment]
Do we want to go into subcommands having separate pages (like `/help [command] [subcommand]` or are we only going down into one level?

**Comment by aiyan** [comment]
@SamHaggans Yeah I thought about that, but I think that might be too much, so 1 level seems perfect.

We could even have each subcommand supply its own help string, and the parent command recursively collects, formats, and outputs all of the help documentation!

**Comment by SamHaggans** [comment]
@aiyan Ok, I agree that 1 level seems good.

And yes, definitely, we don't want to have two separate sets of documentation for the Discord command list and the help list. I can look into this and try to get something out with it.
