### ISSUE TITLE
Allow file upload of new courses

### ISSUE THREAD

**Issue by aiyan** [nu25/hoosky-bot#34]
Allow HooskBot to handle course creation based on a file where each new line is a course to be created.

**Comment by SamHaggans** [comment]
Is this for a server-side file we would add and the bot would read, or something that would be attached to a message?

**Comment by aiyan** [comment]
@SamHaggans Attached to a message! I'm currently implementing this by allowing the user to execute `/course bulk-create` and following up with a file attachment.
