### ISSUE TITLE
Implement countdown

### ISSUE THREAD

**Issue by thederekkaplan** [nu25/hoosky-bot#53]
## Description
Mods can configure a countdown to a date and specify the name of the event to count down to. Every day, the bot announces the the number of days left in the specified channel.
## Tasks
- [x] Daily announcements of all countdowns
- [ ] Documentation
#### Commands:
- [x] `/countdown create [date] [name] [channel]`
- [x] `/countdown list`
- [ ] `/countdown update ?`
- [x] `/countdown delete ?`

"?": see question 1 below
## Questions
1. There should probably be the ability to edit and delete countdowns. How should the command identify countdowns? I'd say by date, but there might be multiple countdowns on the same date. Maybe assign each countdown a unique ID that's shown by `/countdown list`?

**Comment by aiyan** [comment]
Resolved by #59 and subsequent commits.
